Option Strict On
Option Infer On
Imports System.Collections.Immutable
Imports Microsoft.CodeAnalysis
Imports Microsoft.CodeAnalysis.VisualBasic
Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
Imports IGIC = Microsoft.CodeAnalysis.IncrementalGeneratorInitializationContext

<Generator(LanguageNames.VisualBasic)>
Public Class JsonContextGen
    Implements IIncrementalGenerator

    Private Class ClassInfo
        Public Property ClassSyntax As ClassStatementSyntax
        Public Property ClassName As String
        Public Property NamespaceName As String
        Public Property Symbol As ISymbol
    End Class

    Public Sub Initialize(context As IGIC) Implements IIncrementalGenerator.Initialize
        ' Search for classes with GenerateJsonContext attribute
        Dim classDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
            Function(node, cancellationToken)
                ' Look for class declarations
                If TypeOf node IsNot ClassStatementSyntax Then Return False

                Dim classSyntax = DirectCast(node, ClassStatementSyntax)
                ' Check if the class has any attributes
                If classSyntax.AttributeLists.Count = 0 Then Return False

                ' Check if any attribute is GenerateJsonContext
                Return classSyntax.AttributeLists.SelectMany(Function(al) al.Attributes) _
                    .Any(Function(attr) attr.Name.ToString().Contains("GenerateJsonContext"))
            End Function,
            Function(ctx, cancellationToken)
                Dim classSyntax = DirectCast(ctx.Node, ClassStatementSyntax)
                Dim namespaceSyntax = classSyntax.FirstAncestorOrSelf(Of NamespaceBlockSyntax)
                Dim namespaceName = If(namespaceSyntax IsNot Nothing, namespaceSyntax.NamespaceStatement.Name.ToString(), "")

                Return New ClassInfo With {
                    .ClassSyntax = classSyntax,
                    .ClassName = classSyntax.Identifier.Text,
                    .NamespaceName = namespaceName,
                    .Symbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax)
                }
            End Function
        )

        Dim provider = context.CompilationProvider.Combine(classDeclarations.Collect())
        context.RegisterSourceOutput(provider, Sub(spc, source)
                                                   Execute(spc, source.Left, source.Right)
                                               End Sub)
        context.RegisterPostInitializationOutput(
            Sub(ctx)
                ctx.AddSource("GenerateJsonContextAttribute.g.vb", "' <auto-generated>
'     This code was generated by `JsonContextGenerator.VisualBasic`.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Imports System

Public Enum JsonContextOption
    [Default] = 0
    Strict = 1
    Web = 2
End Enum

<AttributeUsage(AttributeTargets.Class, AllowMultiple:=False)>
Public NotInheritable Class GenerateJsonContextAttribute
    Inherits Attribute

    Public ReadOnly Property ContextOption As JsonContextOption

    Public Sub New()
        ContextOption = JsonContextOption.Default
    End Sub

    Public Sub New(jsonCtxOpt As JsonContextOption)
        ContextOption = jsonCtxOpt
    End Sub
End Class")
            End Sub)
    End Sub

    Private Sub Execute(spc As SourceProductionContext, compilation As Compilation, classInfos As ImmutableArray(Of ClassInfo))
        For Each clsInfo In classInfos
            If clsInfo Is Nothing Then Continue For
            Dim semanticModel = compilation.GetSemanticModel(clsInfo.ClassSyntax.SyntaxTree)
            Dim classSymbol = semanticModel.GetDeclaredSymbol(clsInfo.ClassSyntax)
            If classSymbol Is Nothing Then Continue For

            Dim className = classSymbol.Name
            Dim contextClassName = $"{className}JsonContext"
            Dim properties = classSymbol.GetMembers().OfType(Of IPropertySymbol)() _
                .Where(Function(prop) prop.CanBeReferencedByName AndAlso
                    prop.DeclaredAccessibility = Accessibility.Public).ToList()

            Dim sourceCode = GenerateContextClass(clsInfo.NamespaceName, className, contextClassName, properties)
            Dim hintName As String
            Dim nspName = clsInfo.NamespaceName?.Replace(".", "_")
            If String.IsNullOrEmpty(nspName) Then
                hintName = $"{contextClassName}.vb"
            Else
                hintName = $"{nspName}_{contextClassName}.vb"
            End If

            spc.AddSource(hintName, sourceCode)
        Next clsInfo
    End Sub

    Private Function GenerateContextClass(namespaceName As String, typeName As String, contextClassName As String, properties As List(Of IPropertySymbol)) As String
        Dim code As New System.Text.StringBuilder

        code.AppendLine("' <auto-generated>
'     This code was generated by `JsonContextGenerator.VisualBasic`.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>")
        code.AppendLine()
        code.AppendLine("Imports System")
        code.AppendLine("Imports System.Text.Json")
        code.AppendLine("Imports System.Text.Json.Serialization")
        code.AppendLine("Imports System.Text.Json.Serialization.Metadata")
        code.AppendLine("Imports JMS = System.Text.Json.Serialization.Metadata.JsonMetadataServices")
        code.AppendLine()

        If Not String.IsNullOrEmpty(namespaceName) Then
            code.AppendLine($"Namespace {namespaceName}")
            code.AppendLine()
        End If

        code.AppendLine($"Partial Public NotInheritable Class {contextClassName}")
        code.AppendLine("    Inherits JsonSerializerContext")
        code.AppendLine()
        code.AppendLine($"    Private Shared ReadOnly _defaultInstance As New Lazy(Of {contextClassName})(")
        code.AppendLine($"        Function() New {contextClassName}(),")
        code.AppendLine("        System.Threading.LazyThreadSafetyMode.ExecutionAndPublication")
        code.AppendLine("    )")
        code.AppendLine()
        code.AppendLine($"    Public Shared Shadows ReadOnly Property [Default] As {contextClassName}")
        code.AppendLine("        Get")
        code.AppendLine("            Return _defaultInstance.Value")
        code.AppendLine("        End Get")
        code.AppendLine("    End Property")
        code.AppendLine()
        code.AppendLine("    Private Sub New()")
        code.AppendLine("        MyBase.New(LoadOptionsFromAttribute())")
        code.AppendLine("    End Sub")
        code.AppendLine()
        code.AppendLine("    Private Shared Function LoadOptionsFromAttribute() As JsonSerializerOptions")
        code.AppendLine($"        Dim attrib As GenerateJsonContextAttribute = GetType({typeName}) _")
        code.AppendLine("            .GetCustomAttributes(GetType(GenerateJsonContextAttribute), inherit:=False) _")
        code.AppendLine("            .OfType(Of GenerateJsonContextAttribute).FirstOrDefault()")
        code.AppendLine("        Dim options As New JsonSerializerOptions")
        code.AppendLine()
        code.AppendLine("        options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase")
        code.AppendLine("        Select Case If(attrib IsNot Nothing, attrib.ContextOption, JsonContextOption.Default)")
        code.AppendLine("            Case JsonContextOption.Default")
        code.AppendLine("                options.WriteIndented = True")
        code.AppendLine("            Case JsonContextOption.Strict")
        code.AppendLine("                options.PropertyNameCaseInsensitive = False")
        code.AppendLine("                options.IgnoreReadOnlyProperties = True")
        code.AppendLine("            Case JsonContextOption.Web")
        code.AppendLine("                options.PropertyNameCaseInsensitive = True")
        code.AppendLine("                options.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull")
        code.AppendLine("            Case Else")
        code.AppendLine("                Throw New ArgumentException(")
        code.AppendLine("                    ""Invalid JSON context option. Please check the usage of <GenerateJsonContext>."")")
        code.AppendLine("        End Select")
        code.AppendLine()
        code.AppendLine("        Return options")
        code.AppendLine("    End Function")
        code.AppendLine()
        code.AppendLine("    Protected Overrides ReadOnly Property GeneratedSerializerOptions As JsonSerializerOptions")
        code.AppendLine("        Get")
        code.AppendLine("            Return Options")
        code.AppendLine("        End Get")
        code.AppendLine("    End Property")
        code.AppendLine()

        Dim typeInfoFieldName = $"_{Char.ToLower(typeName(0))}{typeName.Substring(1)}_TypeInfo"
        code.AppendLine($"    Private {typeInfoFieldName} As JsonTypeInfo(Of {typeName})")
        code.AppendLine()
        code.AppendLine($"    Public ReadOnly Property {typeName}TypeInfo As JsonTypeInfo(Of {typeName})")
        code.AppendLine("        Get")
        code.AppendLine($"            If {typeInfoFieldName} Is Nothing Then {typeInfoFieldName} = Create{typeName}TypeInfo(Options)")
        code.AppendLine($"            Return {typeInfoFieldName}")
        code.AppendLine("        End Get")
        code.AppendLine("    End Property")
        code.AppendLine($"
    Public Overrides Function GetTypeInfo(type As Type) As JsonTypeInfo
        If type Is Nothing Then Return Nothing
        If type = GetType({typeName}) Then Return {typeName}TypeInfo

        ' Handle all primitive types that might be used
        Select Case Type.GetTypeCode(type)
            Case TypeCode.String
                Return JMS.CreateValueInfo(Of String)(Options, JMS.StringConverter)
            Case TypeCode.Int32
                Return JMS.CreateValueInfo(Of Integer)(Options, JMS.Int32Converter)
            Case TypeCode.Decimal
                Return JMS.CreateValueInfo(Of Decimal)(Options, JMS.DecimalConverter)
            Case TypeCode.Boolean
                Return JMS.CreateValueInfo(Of Boolean)(Options, JMS.BooleanConverter)
            Case TypeCode.DateTime
                Return JMS.CreateValueInfo(Of DateTime)(Options, JMS.DateTimeConverter)
            Case TypeCode.Double
                Return JMS.CreateValueInfo(Of Double)(Options, JMS.DoubleConverter)
            Case TypeCode.Single
                Return JMS.CreateValueInfo(Of Single)(Options, JMS.SingleConverter)
            Case TypeCode.Int64
                Return JMS.CreateValueInfo(Of Long)(Options, JMS.Int64Converter)
            Case TypeCode.Int16
                Return JMS.CreateValueInfo(Of Short)(Options, JMS.Int16Converter)
            Case TypeCode.Byte
                Return JMS.CreateValueInfo(Of Byte)(Options, JMS.ByteConverter)
            Case TypeCode.Char
                Return JMS.CreateValueInfo(Of Char)(Options, JMS.CharConverter)
            Case Else
                Return Nothing
        End Select
    End Function")
        code.AppendLine()
        code.AppendLine($"    Private Shared Function Create{typeName}TypeInfo(options As JsonSerializerOptions) As JsonTypeInfo(Of {typeName})")
        code.AppendLine($"        Dim typeInfo As JsonTypeInfo(Of {typeName}) = JsonTypeInfo.CreateJsonTypeInfo(Of {typeName})(options)")
        code.AppendLine($"        typeInfo.CreateObject = Function() New {typeName}()")
        code.AppendLine()

        For Each prop As IPropertySymbol In properties
            Dim propType = prop.Type.ToDisplayString()
            Dim conversion = GetConversionFromTypeSymbol(prop.Type)

            code.AppendLine($"        Dim prop{prop.Name} As JsonPropertyInfo = typeInfo.CreateJsonPropertyInfo(GetType({propType}), NameOf({typeName}.{prop.Name}))")
            code.AppendLine($"        prop{prop.Name}.Get = Function(obj) DirectCast(obj, {typeName}).{prop.Name}")
            code.AppendLine($"        prop{prop.Name}.Set = Sub(obj, val) DirectCast(obj, {typeName}).{prop.Name} = {conversion}")
            code.AppendLine($"        typeInfo.Properties.Add(prop{prop.Name})")
            code.AppendLine()
        Next prop

        code.AppendLine("        Return typeInfo")
        code.AppendLine("    End Function")
        code.AppendLine()

        code.AppendLine("End Class")

        If Not String.IsNullOrEmpty(namespaceName) Then
            code.AppendLine()
            code.AppendLine("End Namespace")
        End If

        Return code.ToString()
    End Function

    Private Function GetConversionFromTypeSymbol(typeSymbol As ITypeSymbol) As String
        Dim typeName = typeSymbol.ToDisplayString()

        Select Case typeName
            Case "String"
                Return "CStr(val)"
            Case "Integer"
                Return "CInt(val)"
            Case "Double"
                Return "CDbl(val)"
            Case "Single"
                Return "CSng(val)"
            Case "Decimal"
                Return "CDec(val)"
            Case "Long"
                Return "CLng(val)"
            Case "Short"
                Return "CShort(val)"
            Case "Byte"
                Return "CByte(val)"
            Case "Boolean"
                Return "CBool(val)"
            Case "Char"
                Return "CChar(val)"
            Case "DateTime"
                Return "CDate(val)"
            Case Else
                Return $"CType(val, {typeName})"
        End Select
    End Function
End Class